### ISSUE TITLE
Android - Download Files

### ISSUE THREAD

**Issue by 604naz** [nautilusdigital/collabo-issues#6] opened 2017-10-26 20:29 UTC
Android S7 - Samsung

Can't find files once they are downloaded

Need the ability to choose all files or filter by user group and select multiple. One at a time...no bueno

**Comment by Collabophotos** [comment] 2017-10-27 05:42
Same thin on Pixel phone.  Went to photos and was not there.  Had to go into files and find the downloaded file to find.  Screenshot reads "this file type is unsupported" Was ok to open in google photos however.  @604Naz.  what was the file size of the picture you uploaded.  The one I downloaded was 304 kB.

![screenshot_20171026-223604](https://user-images.githubusercontent.com/33112490/32089433-d0b269ee-ba9e-11e7-8887-b523948c024e.png)

**Comment by mhousser** [comment] 2017-10-27 05:51
I think I know what the problem is for file type not supported. I have a
fix in mind.

**Comment by mhousser** [comment] 2017-10-27 06:18
@604naz @Collabophotos Could you try again to see if the `This file type is unsupported` error still occurs with a freshly downloaded photo? The downloaded photos were missing a `jpg` extension and so perhaps the mobile OS was confused about how to open it.

**Comment by mhousser** [comment] 2017-10-27 06:20
Note that this fix to `This file type is unsupported` does not require client-side changes, so it should work without an app update.

**Comment by Collabophotos** [comment] 2017-10-27 06:24
Same thing. On iPhone I have no idea if the pictures downloaded.  Can't
find them anywhere on my phone

**Comment by Collabophotos** [comment] 2017-10-27 06:29
But it still reads unsupported

**Comment by mhousser** [comment] 2017-10-27 06:37
@Collabophotos confused if you're talking about Android or iOS. "Unsupported" is on Android? Prod or Staging?

I just checked 3 files and hit 'Download' in iOS latest Beta build (Staging), and the files are now visible in the iOS Photos app:

![img_20171026_233454](https://user-images.githubusercontent.com/832078/32090883-877cb664-baa6-11e7-98d6-a4f6081c40bf.jpg)

**Comment by Collabophotos** [comment] 2017-10-27 06:39
Production android is where I tried to download
Production iOS tried to download but not sure where the pictures are as
they don't go into my gallery

**Comment by mhousser** [comment] 2017-10-27 06:48
@Collabophotos you are right, in iOS latest Beta I *can* see the downloaded images in Photos, but in iOS latest production (1.0.1), I can *not* see the downloaded images in Photos. I think @aethusn must have fixed something related to iOS image downloading that isn't in the store yet.

**Comment by mhousser** [comment] 2017-10-27 06:57
@Collabophotos in Android Production I am not seeing "Unsupported" any more. Note that old images you already download may still say unsupported - new downloads only.

However @vivanov1410 I'm not finding them locally in Photos on Android - they seem to be only findable in the "Downloads" app. It's apparently not being correctly broadcast to Android. It's probably not being put in correct external storage directory (should be a Collabo directory). 

Also @vivanov1410 the file names are all "Download successful".

**Comment by mhousser** [comment] 2017-10-27 06:58
3 simultaneous downloads in Android production, followed by finding them in Downloads (several things need to be fixed):

![screenshot_20171026-235130](https://user-images.githubusercontent.com/832078/32091543-8630853a-baa9-11e7-9fff-496af32c595a.png)
![screenshot_20171026-235741](https://user-images.githubusercontent.com/832078/32091546-88ee2642-baa9-11e7-8162-bd9a2c41e5a4.png)

**Comment by Collabophotos** [comment] 2017-10-30 23:28
Did we sort out the fix for where the photos in production android is going to?

**Comment by Collabophotos** [comment] 2017-10-31 03:40
new downloads on production Android - still going to download file and savings as a document.     File name is no longer download successful.  Images where taken with iphone but the file name is a very long string of letters and numbers. "this file type is unsupported." is still happening. The option to open with... when i choose open in photos, metadata intact and confirms image is being saved in document folder.

**Comment by mhousser** [comment] 2017-11-10 22:04
Closing. Fixed.

**Closed by mhousser** 2017-11-10 22:04 UTC
